database:
    driverClass: com.mysql.jdbc.Driver
    user: phonebookuser
    password: phonebookpassword
    url: jdbc:mysql://localhost/phonebook
    
server:
  applicationConnectors:
  - type: http 
    port: 9000
  adminConnectors:
  - type: http
    port: 9001